### ISSUE TITLE
Bug: Redraw on resize not working properly

### ISSUE THREAD

**Issue by marcflp** [dcasia/chartjs-widget#1]
While resizing chart widgets, redraw resized the width, but height doesn't resize until refresh.

For reference:
https://codepen.io/apertureless/pen/jZOBeV?editors=1010

**Comment by milewski** [comment]
Hey when I resize it on the link you shared above it works correctly for me... maybe this is a browser issue? I'm using the latest version of chrome

**Comment by marcflp** [comment]
> Hey when I resize it on the link you shared above it works correctly for me... maybe this is a browser issue? I'm using the latest version of chrome

The link I gave was for reference that it can work, I can't find any difference, but somehow with your widget it doesn't work. My knowledge of vue isn't that great though, so perhaps you can find the culprit.

**Comment by milewski** [comment]
Can you share a gif/video of what is happening for you? my dashboard works exactly the same as on the link you shared

**Comment by marcflp** [comment]
![chartjs-widget-height](https://user-images.githubusercontent.com/1815234/89047093-35199400-d34e-11ea-9e12-d707b433de65.gif)

**Comment by milewski** [comment]
Well that doesn't happen to me.. can you share the settings you use so I can try to reproduce it locally

**Comment by milewski** [comment]
Also I noticed that this doesn't looks right... are you using any sort of theme? or overriding some nova defaults css?

![image](https://user-images.githubusercontent.com/2874967/89047523-1a144780-d381-11ea-94c3-c93199b8f8f1.png)

**Comment by marcflp** [comment]
Only thing that might adjust some css is https://novapackages.com/packages/gregoriohc/laravel-nova-theme-responsive

**Comment by milewski** [comment]
I installed that package and also had no issues.... Might be some other settings or a browser version issue.. 

However, I made a change on the code just now can you try again? I am calling `chartjs.update()` every time the width/height changes... see if this can solve this issue

**Comment by marcflp** [comment]
That fixed it!
