### ISSUE TITLE
Request: Plugin for ChartJS

### ISSUE THREAD

**Issue by marcflp** [dcasia/chartjs-widget#3]
Instead of specifying colors, would be nice if it's possible to utilize https://github.com/nagix/chartjs-plugin-colorschemes and just choose a color scheme in the options window.

**Comment by milewski** [comment]
Nice! I didn't know about this one.. I will try to integrate it see the best way to have presets and still allow manual override

**Comment by milewski** [comment]
Done! ... usage:

```php
(new LineChartWidget())->colorScheme('office.Metro6')
```

Or manually input from the create/update modal:

![image](https://user-images.githubusercontent.com/2874967/89043566-3e6d2580-d37b-11ea-8422-1ca1a38e07cb.png)

Also, it is possible to override a single color from the border for example by setting it as usual on the Option object
