### ISSUE TITLE
LOG.error: Invalid number of arguments, expected: { int $x, int $y, int $width, int $height } or none. 

### ISSUE THREAD

**Issue by xoco70** [dcasia/chartjs-widget#4]
Hi, 

I am able to render a chart using "editable()" mode by using branches dev-master in composer for both nova dashboard and nova chartjs-widget.

What I cannot achieve anymore is passing the $options variable into the `widgets()` method in my view.

When I try to pass a fifth argument with options, I get:

`LOG.error: Invalid number of arguments, expected: { int $x, int $y, int $width, int $height } or none. `

How should I pass static `$option` to my graph ?

**Comment by milewski** [comment]
No longer an issue on the latest version, I have rewritten everything...
