### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by devlsh** [dcasia/chartjs-widget#8]
Hey,

I love the idea of this package, but was unable to get it working with nova-dashboard - it seems there area bunch of changes since the initial idea was released

I know it's still a work-in-progress, but do you have any idea as to when you'd look at releasing (And documenting) this package? It's the only thing keeping me from switching to nova-dashboard

Thanks!

**Comment by cord** [comment]
works with "dev-master" - it is working as part of

https://novapackages.com/packages/nova-bi/nova-dashboard-manager

**Comment by milewski** [comment]
After years now it is no longer a work-in-progress... it is finally done 😆
