### ISSUE TITLE
chart not showing

### ISSUE THREAD

**Issue by Pamposgsk** [dcasia/chartjs-widget#9]
![chartjserror](https://user-images.githubusercontent.com/8403769/99934142-d5fce680-2d65-11eb-8b32-3b8e429832f3.jpg)

Hi i cannot add this widget to the dashboard view.
Could you please give some more info on how to use this widget?

**Comment by cord** [comment]
you need to use `dev-master` for all packages, with https://novapackages.com/packages/nova-bi/nova-dashboard-manager you get a working setup

**Comment by milewski** [comment]
Not an issue anymore on latest version
